#!/bin/bash

# Instala el servicio de compartición en red local SAMBA

sudo apt install samba samba-common-bin -y

# Copia la configuración para compartir la carpeta Pictures
sudo cp smb.conf /etc/samba/

# Establece contraseña para el usuario PI. Hay que introducir la contraseña dos veces.

sudo smbpasswd -a pi

# Reinicia y activa el servicio SAMBA en el equipo

sudo systemctl restart smbd
sudo systemctl enable smbd

# Instala el visor de imágenes

sudo apt-get install feh -y
cp Escudo.jpg /home/pi/Pictures

# Copiar el archivo que lanza el navegador en modo kiosk en cada inicio

sudo cp chromium-kiosk-pi.desktop /etc/xdg/autostart

# Copiar los servicios de dispositivas y navegador en modo kiosko 
# por segunda vez en el día

sudo cp slideshow.* /etc/systemd/system
sudo cp chromiumkiosk.* /etc/systemd/system
sudo cp shutdowntimer* /etc/systemd/system

# Recarga los servicios del sistema
sudo systemctl daemon-reload

# Inicia los servicios timer para que se ejecuten a una hora específica
# y los servicios de diapositivas y chromium en modo kiosk

#sudo systemctl start slideshow.service
sudo systemctl enable slideshow.timer
sudo systemctl start slideshow.timer
#sudo systemctl start chromiumkiosk.service
sudo systemctl enable chromiumkiosk.timer
sudo systemctl start chromiumkiosk.timer
sudo systemctl enable shutdowntimer.timer
sudo systemctl start shutdowntimer.timer
#sudo systemctl start shutdowntimer.service

