#!/bin/bash

# Copiar el archivo que lanza el navegador en modo kiosk en cada inicio
sudo cp chromium-kiosk-pi.desktop /etc/xdg/autostart

# Copiar los servicios de dispositivas y navegador en modo kiosko 
# por segunda vez en el día
sudo cp slideshow.* /etc/systemd/system
sudo cp chromiumkiosk.* /etc/systemd/system

# Recarga los servicios del sistem
sudo systemctl daemon-reload

# Inicia los servicios timer para que se ejecuten a una hora específica
# y los servicios de diapositivas y chromium en modo kiosk
#sudo systemctl start slideshow.service
sudo systemctl enable slideshow.timer
sudo systemctl start slideshow.timer
#sudo systemctl start chromiumkiosk.service
sudo systemctl enable chromiumkiosk.timer
sudo systemctl start chromiumkiosk.timer

